<?php

namespace App\Tests;

use App\Tests\SetUp\DomainTestCase;
use Symfony\Component\HttpFoundation\Response;

class ClientTest extends DomainTestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->loadTestDatabase();
    }

    public function testAnewClientCanRegister(): void
    {
        $client = $this->runAsAdminWithBasicAuth();
        $client->request('POST', '/api/client/register' , array(
            'name' => 'test'
        ));
        $this->assertSame(Response::HTTP_CREATED, $client->getResponse()->getStatusCode());
    }

    public function testAnAuthenticatedClientCanGetThePublicKey(): void
    {
        $client = $this->runAsClient();
        $client->request('POST', '/api/client/key');
        $this->assertSame(Response::HTTP_OK, $client->getResponse()->getStatusCode());
    }
}
