<?php
/**
 * Created by PhpStorm.
 * User: BlackBit
 * Date: 13-Dec-18
 * Time: 19:44
 */

namespace App\Tests;

use App\Tests\SetUp\DomainTestCase;
use Authentication\Resources\DataFixtures\UserFixture;
use Symfony\Component\HttpFoundation\Response;

class UserTest extends DomainTestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->loadTestDatabase();
    }



    public function testAnewUserCanRegister(): void
    {
        $client = self::createClient();
        $client->request('POST', '/api/user/register' , array(
            'email' => 'test@test.com',
            'password' => 'test',
            'username' => 'test',
            'agreementSigned' => 1
        ));
        $this->assertSame(Response::HTTP_CREATED, $client->getResponse()->getStatusCode());
    }

    public function testAnewUserCanNotRegisterWithTakenCredentials(): void
    {
        $client = self::createClient();
        $client->request('POST', '/api/user/register' , array(
            'email' => 'test@test.com',
            'password' => 'test',
            'username' => UserFixture::USER_USERNAME,
            'agreementSigned' => 1
        ));
        $this->assertSame(Response::HTTP_CONFLICT, $client->getResponse()->getStatusCode());
        $client->request('POST', '/api/user/register' , array(
            'email' => UserFixture::USER_EMAIL,
            'password' => 'test',
            'username' => 'test',
            'agreementSigned' => 1
        ));
        $this->assertSame(Response::HTTP_CONFLICT, $client->getResponse()->getStatusCode());
    }
}
